#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "Running lightweight pre-commit checks..."

mvn -DskipTests=true \
    -Dskip.npm=true \
    -Dfrontend.skip=true \
    -Dskip.installnodenpm=true \
    verify
